name: Get Runner Labels

on:
  workflow_call:
    outputs:
      LINUX_RUNNER_LABELS:
        description: "linux runner labels"
        value: ${{ jobs.main.outputs.LINUX_RUNNER_LABELS }}
      MACOS_RUNNER_LABELS:
        description: "macos runner labels"
        value: ${{ jobs.main.outputs.MACOS_RUNNER_LABELS }}
      WINDOWS_RUNNER_LABELS:
        description: "windows runner labels"
        value: ${{ jobs.main.outputs.WINDOWS_RUNNER_LABELS }}

jobs:
  main:
    name: Get Runner Labels
    runs-on: ubuntu-latest
    outputs:
      LINUX_RUNNER_LABELS: ${{ steps.run.outputs.LINUX_RUNNER_LABELS }}
      MACOS_RUNNER_LABELS: ${{ steps.run.outputs.MACOS_RUNNER_LABELS }}
      WINDOWS_RUNNER_LABELS: ${{ steps.run.outputs.WINDOWS_RUNNER_LABELS }}
    steps:
      - id: run
        shell: bash
        run: |
          ref_name="${{ github.ref_name }}"
          # set default value for vars.XXX_RUNNER_LABELS
          LINUX_RUNNER_LABELS='${{ vars.LINUX_RUNNER_LABELS || '"ubuntu-latest"' }}'
          MACOS_RUNNER_LABELS='${{ vars.MACOS_RUNNER_LABELS || '"macos-latest"' }}'
          WINDOWS_RUNNER_LABELS='${{ vars.WINDOWS_RUNNER_LABELS || '"windows-latest"' }}'
          WINDOWS_RUNNER_LABELS='["Windows","ci"]'
          MACOS_RUNNER_LABELS='["macOS","ci"]'
          # if ref name is main, run it on github runner
          if [[ "$ref_name" == "main" ]]; then
            LINUX_RUNNER_LABELS='"ubuntu-latest"'
            MACOS_RUNNER_LABELS='"macos-latest"'
            WINDOWS_RUNNER_LABELS='"windows-latest"'
          fi
          # export XXX_RUNNER_LABELS to output
          echo "LINUX_RUNNER_LABELS=$LINUX_RUNNER_LABELS" >> "$GITHUB_OUTPUT"
          echo "MACOS_RUNNER_LABELS=$MACOS_RUNNER_LABELS" >> "$GITHUB_OUTPUT"
          echo "WINDOWS_RUNNER_LABELS=$WINDOWS_RUNNER_LABELS" >> "$GITHUB_OUTPUT"
